# Generated by Django 5.0.3 on 2024-07-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
